### ISSUE TITLE
Does not connect (?)

### ISSUE THREAD

**Issue by opticbird** [GuckTubeYT/GTBotLinux#2]
I edited the source to get it working on windows but it does not connect? Where should I look for to fix this?

**Comment by GuckTubeYT** [comment]
Wdym not connect? You mean = cant connect to real gt server?

**Comment by opticbird** [comment]
> Wdym not connect? You mean = cant connect to real gt server?

It says "Connecting to server". So, it tries to connect. But it just disconnects, it might rarely say "connected" but even then nothing happens and it disconnects again. Also it won't enter to a world. (can't see anything in console if it gets  connected)

**Comment by GuckTubeYT** [comment]
Try re download gtbotlinux

**Comment by opticbird** [comment]
> Try re download gtbotlinux

![kuva_2021-08-07_110650](https://user-images.githubusercontent.com/61664355/128593466-07ca1c85-8a0c-4fee-87f8-05b5a342f24b.png)

**Comment by GuckTubeYT** [comment]
did you make usingNewPacket = true?

**Comment by opticbird** [comment]
> did you make usingNewPacket = true?
Yes. 
	client = enet_host_create(NULL /* create a client host */,
			1 /* only allow 1 outgoing connection */,
			2 /* allow up 2 channels to be used, 0 and 1 */,
			0 /* 56K modem with 56 Kbps downstream bandwidth */,
			0 /* 56K modem with 14 Kbps upstream bandwidth */);
		client->usingNewPacket = true;

**Comment by GuckTubeYT** [comment]
Hmmmmm... opticbird, try use gtbot windows version, and then replace to gtbot linux

**Comment by GuckTubeYT** [comment]
Or you cant use this on windows, because this is only linux

**Comment by GuckTubeYT** [comment]
Sorry bad grammar
