### ISSUE TITLE
how to connect to gt real, i mean the ip gt real?

### ISSUE THREAD

**Issue by Koahsi** [GuckTubeYT/GTBotLinux#3]

**Comment by GuckTubeYT** [comment]
just input the gt real ip and port

**Comment by Koahsi** [comment]
> just input the gt real ip and port

how to check...

**Comment by GuckTubeYT** [comment]
> 
> 
> > just input the gt real ip and port
> 
> how to check...

goto http://growtopia1.com/growtopia/server_data.php
